### ISSUE TITLE
bdf/b10.bdfの作成方法

### ISSUE THREAD

**Issue by matsujirushi** [tanakamasayuki/u8g2_font_ilfont#1]
[こちら](https://twitter.com/matsujirushi12/status/1437972503058542595)の事象で、リテラル文字列を使わないと効率が良いのか悪いのかを確認しようとしています。

（bdfconvのソースを修正して）tool/build_efont_ja.batを実行したいのですが、bdf/b10.bdfやbdf/b10_b.bdfなどがリポジトリに含まれていないためエラーが発生しています。

bdf/b10.bdfなどをリポジトリに追加いただけないでしょうか？
もしくは、生成のバッチファイルを教えていただけませんか？

**Comment by tanakamasayuki** [comment]
https://moji.or.jp/ipafont/

フォントそのもののデータなので上記よりダウンロードお願いします。

**Comment by tanakamasayuki** [comment]
フォントそのものを変換したファイルなので

https://moji.or.jp/ipafont/

上記よりttfファイルをダウンロードして

TTF to BDF
otf2bdf 3.1(http://sofia.nmsu.edu/~mleisher/Software/otf2bdf/)

このツールで変換していただきたいと思います。
コマンドは「./otf2bdf -r 72 -p 8 -o ilfontm_8.bdf ipam.ttf」などと書いてあるコマンドになります。
Winだと失敗して、Linux上で変換したように覚えています

**Comment by tanakamasayuki** [comment]
すみません、よくみたらそのファイルだけ入っていなくて、出力にもいませんね。。。
10ドットはいらないだろうって抜いたのか、単に入れ忘れていたのか思い出せません、、、

**Comment by matsujirushi** [comment]
情報ありがとうございます！
フォントの提供元、変換について理解していないものですから、大変助かります。
やってみます。
